/*
 * This file is generated by jOOQ.
 */
package com.hieplp.lrt.repositories.generate.tables.daos;


import com.hieplp.lrt.repositories.generate.tables.User;
import com.hieplp.lrt.repositories.generate.tables.records.UserRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import java.time.LocalDateTime;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class UserDao extends DAOImpl<UserRecord, com.hieplp.lrt.repositories.generate.tables.pojos.User, String> {

    /**
     * Create a new UserDao without any configuration
     */
    public UserDao() {
        super(User.USER, com.hieplp.lrt.repositories.generate.tables.pojos.User.class);
    }

    /**
     * Create a new UserDao with an attached configuration
     */
    public UserDao(Configuration configuration) {
        super(User.USER, com.hieplp.lrt.repositories.generate.tables.pojos.User.class, configuration);
    }

    @Override
    public String getId(com.hieplp.lrt.repositories.generate.tables.pojos.User object) {
        return object.getUserid();
    }

    /**
     * Fetch records that have <code>userId BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.hieplp.lrt.repositories.generate.tables.pojos.User> fetchRangeOfUserid(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.USERID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>userId IN (values)</code>
     */
    public List<com.hieplp.lrt.repositories.generate.tables.pojos.User> fetchByUserid(String... values) {
        return fetch(User.USER.USERID, values);
    }

    /**
     * Fetch a unique record that has <code>userId = value</code>
     */
    public com.hieplp.lrt.repositories.generate.tables.pojos.User fetchOneByUserid(String value) {
        return fetchOne(User.USER.USERID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.hieplp.lrt.repositories.generate.tables.pojos.User> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.hieplp.lrt.repositories.generate.tables.pojos.User> fetchByName(String... values) {
        return fetch(User.USER.NAME, values);
    }

    /**
     * Fetch records that have <code>personalId BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.hieplp.lrt.repositories.generate.tables.pojos.User> fetchRangeOfPersonalid(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.PERSONALID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>personalId IN (values)</code>
     */
    public List<com.hieplp.lrt.repositories.generate.tables.pojos.User> fetchByPersonalid(String... values) {
        return fetch(User.USER.PERSONALID, values);
    }

    /**
     * Fetch a unique record that has <code>personalId = value</code>
     */
    public com.hieplp.lrt.repositories.generate.tables.pojos.User fetchOneByPersonalid(String value) {
        return fetchOne(User.USER.PERSONALID, value);
    }

    /**
     * Fetch records that have <code>phone BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.hieplp.lrt.repositories.generate.tables.pojos.User> fetchRangeOfPhone(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.PHONE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<com.hieplp.lrt.repositories.generate.tables.pojos.User> fetchByPhone(String... values) {
        return fetch(User.USER.PHONE, values);
    }

    /**
     * Fetch a unique record that has <code>phone = value</code>
     */
    public com.hieplp.lrt.repositories.generate.tables.pojos.User fetchOneByPhone(String value) {
        return fetchOne(User.USER.PHONE, value);
    }

    /**
     * Fetch records that have <code>createdBy BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.hieplp.lrt.repositories.generate.tables.pojos.User> fetchRangeOfCreatedby(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.CREATEDBY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>createdBy IN (values)</code>
     */
    public List<com.hieplp.lrt.repositories.generate.tables.pojos.User> fetchByCreatedby(String... values) {
        return fetch(User.USER.CREATEDBY, values);
    }

    /**
     * Fetch records that have <code>createdAt BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.hieplp.lrt.repositories.generate.tables.pojos.User> fetchRangeOfCreatedat(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(User.USER.CREATEDAT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>createdAt IN (values)</code>
     */
    public List<com.hieplp.lrt.repositories.generate.tables.pojos.User> fetchByCreatedat(LocalDateTime... values) {
        return fetch(User.USER.CREATEDAT, values);
    }

    /**
     * Fetch records that have <code>modifiedBy BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.hieplp.lrt.repositories.generate.tables.pojos.User> fetchRangeOfModifiedby(String lowerInclusive, String upperInclusive) {
        return fetchRange(User.USER.MODIFIEDBY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modifiedBy IN (values)</code>
     */
    public List<com.hieplp.lrt.repositories.generate.tables.pojos.User> fetchByModifiedby(String... values) {
        return fetch(User.USER.MODIFIEDBY, values);
    }

    /**
     * Fetch records that have <code>modifiedAt BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.hieplp.lrt.repositories.generate.tables.pojos.User> fetchRangeOfModifiedat(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(User.USER.MODIFIEDAT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modifiedAt IN (values)</code>
     */
    public List<com.hieplp.lrt.repositories.generate.tables.pojos.User> fetchByModifiedat(LocalDateTime... values) {
        return fetch(User.USER.MODIFIEDAT, values);
    }
}
