export const SUCCESS_CODE = {
	OK: "200",
	SSE_SUCCESS: "SSE_200",
}

export const ERROR_CODE = {
	BAD_REQUEST: "400",
	//
	DUPLICATED_PHONE: "USER_4000",
	DUPLICATED_PERSONAL_ID: "USER_4001",
	NO_USER_SELECTED: "USER_4002",
	//
	SSE_SERVER_ERROR: "SSE_500",
}
