/*
 * This file is generated by jOOQ.
 */
package com.hieplp.lrt.repositories.generate.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    private String userid;
    private String name;
    private String personalid;
    private String phone;
    private String createdby;
    private LocalDateTime createdat;
    private String modifiedby;
    private LocalDateTime modifiedat;

    public User() {
    }

    public User(User value) {
        this.userid = value.userid;
        this.name = value.name;
        this.personalid = value.personalid;
        this.phone = value.phone;
        this.createdby = value.createdby;
        this.createdat = value.createdat;
        this.modifiedby = value.modifiedby;
        this.modifiedat = value.modifiedat;
    }

    public User(
            String userid,
            String name,
            String personalid,
            String phone,
            String createdby,
            LocalDateTime createdat,
            String modifiedby,
            LocalDateTime modifiedat
    ) {
        this.userid = userid;
        this.name = name;
        this.personalid = personalid;
        this.phone = phone;
        this.createdby = createdby;
        this.createdat = createdat;
        this.modifiedby = modifiedby;
        this.modifiedat = modifiedat;
    }

    /**
     * Getter for <code>longTask.user.userId</code>.
     */
    public String getUserid() {
        return this.userid;
    }

    /**
     * Setter for <code>longTask.user.userId</code>.
     */
    public User setUserid(String userid) {
        this.userid = userid;
        return this;
    }

    /**
     * Getter for <code>longTask.user.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>longTask.user.name</code>.
     */
    public User setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>longTask.user.personalId</code>.
     */
    public String getPersonalid() {
        return this.personalid;
    }

    /**
     * Setter for <code>longTask.user.personalId</code>.
     */
    public User setPersonalid(String personalid) {
        this.personalid = personalid;
        return this;
    }

    /**
     * Getter for <code>longTask.user.phone</code>.
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>longTask.user.phone</code>.
     */
    public User setPhone(String phone) {
        this.phone = phone;
        return this;
    }

    /**
     * Getter for <code>longTask.user.createdBy</code>.
     */
    public String getCreatedby() {
        return this.createdby;
    }

    /**
     * Setter for <code>longTask.user.createdBy</code>.
     */
    public User setCreatedby(String createdby) {
        this.createdby = createdby;
        return this;
    }

    /**
     * Getter for <code>longTask.user.createdAt</code>.
     */
    public LocalDateTime getCreatedat() {
        return this.createdat;
    }

    /**
     * Setter for <code>longTask.user.createdAt</code>.
     */
    public User setCreatedat(LocalDateTime createdat) {
        this.createdat = createdat;
        return this;
    }

    /**
     * Getter for <code>longTask.user.modifiedBy</code>.
     */
    public String getModifiedby() {
        return this.modifiedby;
    }

    /**
     * Setter for <code>longTask.user.modifiedBy</code>.
     */
    public User setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby;
        return this;
    }

    /**
     * Getter for <code>longTask.user.modifiedAt</code>.
     */
    public LocalDateTime getModifiedat() {
        return this.modifiedat;
    }

    /**
     * Setter for <code>longTask.user.modifiedAt</code>.
     */
    public User setModifiedat(LocalDateTime modifiedat) {
        this.modifiedat = modifiedat;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(userid);
        sb.append(", ").append(name);
        sb.append(", ").append(personalid);
        sb.append(", ").append(phone);
        sb.append(", ").append(createdby);
        sb.append(", ").append(createdat);
        sb.append(", ").append(modifiedby);
        sb.append(", ").append(modifiedat);

        sb.append(")");
        return sb.toString();
    }
}
