/*
 * This file is generated by jOOQ.
 */
package com.hieplp.lrt.repositories.generate;


import com.hieplp.lrt.repositories.generate.tables.User;
import com.hieplp.lrt.repositories.generate.tables.records.UserRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * longTask.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, DSL.name("KEY_user_PRIMARY"), new TableField[]{User.USER.USERID}, true);
    public static final UniqueKey<UserRecord> KEY_USER_USER_PERSONALID_UINDEX = Internal.createUniqueKey(User.USER, DSL.name("KEY_user_user_personalId_uindex"), new TableField[]{User.USER.PERSONALID}, true);
    public static final UniqueKey<UserRecord> KEY_USER_USER_PHONE_UINDEX = Internal.createUniqueKey(User.USER, DSL.name("KEY_user_user_phone_uindex"), new TableField[]{User.USER.PHONE}, true);
}
