/*
 * This file is generated by jOOQ.
 */
package com.hieplp.lrt.repositories.generate;


import com.hieplp.lrt.repositories.generate.tables.User;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Longtask extends SchemaImpl {

    /**
     * The reference instance of <code>longTask</code>
     */
    public static final Longtask LONGTASK = new Longtask();
    private static final long serialVersionUID = 1L;
    /**
     * The table <code>longTask.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Longtask() {
        super("longTask", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
                User.USER
        );
    }
}
