/*
 * This file is generated by jOOQ.
 */
package com.hieplp.lrt.repositories.generate;


import com.hieplp.lrt.repositories.generate.tables.User;


/**
 * Convenience access to all tables in longTask.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>longTask.user</code>.
     */
    public static final User USER = User.USER;
}
